language: node_js
node_js:
- '8'
cache: yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: lucmartens92@gmail.com
  api_key:
    secure: FgBEcbU1VZVkPt0AYKN3/OdXyVjE6e9oxb68Jx2O5wON9W+04ZIsT9y+r0OuQ+mAlRDrAjjYlnCWkKRxSE3afux+RxQEuPO7qGkV6di+RjywvD8ioSRsj6PEdYYqZjJfXPOQFnhJSsaH+49Mgz/3pC3xwQU+8y4scTMzGEUQ+qB9yxsC0/O1RLGpvWat7M6eYkEESrqEl4SRArp1Li2K5quTh5KVZVX3LF+ZlMvVpLTR7yaKVn1KK8KCAbjUd/FRSqp/wkIaUnfTV7CnKY3gWpv2zfoAEx0P0WA/3kDKaO4BDgmQuTj0He8hyz/8AYMICSCI2jyZ78ZceKr6abN6kOyIjTgHf73InYNtB/tAs9pn/+67GDRhSbdZnvjCgPPBUC2mRtURUV+CSQ3tYLclIt8lsJeM9bS1uzHpGI7B03iXP2OmCbdODBg9npZ7m2bpzazYMp9tSrDQztKBKVkZ9zFfO//O1VMSGpzzucSGV8uky+PssG70jnP3YmRXAPpCpS7aXZsSiLhlZD2KPGWjnjEIlruQB1ZKXU3bpcu3X00G3FZTLM8uvxWjx4I41MqTZMijoZQM6LX2PaM4J8BiTQhTvhCNONdRtJ7jT4CIb5lEGSwL793pK1miN+gZyGG8rQkiyLP60K6AN/p+rsRCASTxiKlhCEq+i3yfHILsDCc=
  on:
    repo: lucmartens/xstate-plantuml
    tags: true
