@startuml
left to right direction
state "download" as download {
  [*] --> download.idle

  state "idle" as download.idle {
    download.idle --> download.downloading : START\l[stableConnection]\l/startDownload
  }

  state "downloading" as download.downloading {
    download.downloading : do/streamChunks
    download.downloading --> download.paused : PAUSE
    download.downloading --> download.finished : DONE
  }

  state "paused" as download.paused {
    download.paused --> download.downloading : RESUME\l/resumeDownload
    download.paused --> download.finished : CANCEL
  }

  state "finished" as download.finished {
    download.finished : onEntry/cleanCache
  }
}
@enduml
