@startuml
left to right direction
state "internal" as internal {
  [*] --> internal.a

  internal --> internal.a : A
  internal --> internal.b : B
  internal --> internal.c : C
  state "a" as internal.a {
  }

  state "b" as internal.b {
  }

  state "c" as internal.c {
  }
}
@enduml
