@startuml
left to right direction
state "machine" as machine {
  [*] --> machine.initial

  state "initial" as machine.initial {
    machine.initial --> machine.final : always
  }

  state "final" as machine.final {
  }
}
@enduml
