@startuml
left to right direction
state "wordmachine" as wordmachine {
  state "bold" as wordmachine.bold {
    [*] --> wordmachine.bold.off

    state "on" as wordmachine.bold.on {
      wordmachine.bold.on --> wordmachine.bold.off : TOGGLE_BOLD
    }

    state "off" as wordmachine.bold.off {
      wordmachine.bold.off --> wordmachine.bold.on : TOGGLE_BOLD
    }
  }

  state "underline" as wordmachine.underline {
    [*] --> wordmachine.underline.off

    state "on" as wordmachine.underline.on {
      wordmachine.underline.on --> wordmachine.underline.off : TOGGLE_UNDERLINE
    }

    state "off" as wordmachine.underline.off {
      wordmachine.underline.off --> wordmachine.underline.on : TOGGLE_UNDERLINE
    }
  }

  state "italics" as wordmachine.italics {
    [*] --> wordmachine.italics.off

    state "on" as wordmachine.italics.on {
      wordmachine.italics.on --> wordmachine.italics.off : TOGGLE_ITALICS
    }

    state "off" as wordmachine.italics.off {
      wordmachine.italics.off --> wordmachine.italics.on : TOGGLE_ITALICS
    }
  }

  state "list" as wordmachine.list {
    [*] --> wordmachine.list.none

    state "none" as wordmachine.list.none {
      wordmachine.list.none --> wordmachine.list.bullets : BULLETS
      wordmachine.list.none --> wordmachine.list.numbers : NUMBERS
    }

    state "bullets" as wordmachine.list.bullets {
      wordmachine.list.bullets --> wordmachine.list.none : NONE
      wordmachine.list.bullets --> wordmachine.list.numbers : NUMBERS
    }

    state "numbers" as wordmachine.list.numbers {
      wordmachine.list.numbers --> wordmachine.list.bullets : BULLETS
      wordmachine.list.numbers --> wordmachine.list.none : NONE
    }
  }
}
@enduml
