@startuml
    state "light" as light {
        state "green" as light_green
        state "yellow" as light_yellow
        state "red" as light_red
        [*] --> light_green 
        light_green --> light_yellow : TIMER
        light_yellow --> light_red : TIMER
        light_red --> light_green : TIMER
    }
@enduml
